["protostar.config"]
protostar_version = "0.3.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
deployer = [
    "src/deployer.cairo",
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]
