["protostar.config"]
protostar_version = "0.3.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
deployer = [
    "src/deployer.cairo",
]

OZ_ERC721MintableBurnable = [
    "./lib/cairo_contracts/src/openzeppelin/token/erc721/presets/ERC721MintableBurnable.cairo"
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]
